name: Version Bump

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ— Setup repo
      uses: actions/checkout@v3

    - name: ğŸ“¦ Enable Corepack
      run: corepack enable

    - name: ğŸ— Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: yarn
        
    - name: ğŸ“¦ Install Project dependencies
      run: yarn install --immutable --mode=skip-build
      
    - name: ğŸ—ï¸ Build bump-please-core
      run: yarn workspace bump-please-core build
      
    - name: ğŸ—ï¸ Build bump-please
      run: yarn workspace bump-please build
                
    - name: ğŸ¤œ Bump Please
      uses: chriswoodle/bump-please-action@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-committer-name: github-actions[bot]
        git-committer-email: github-actions[bot]@users.noreply.github.com
    